import {
  AttendanceRecord,
  ClassSlot,
  CourseInfo,
  OverallAttendance,
  StudentProfile,
  TimetableEntry,
} from '../../types';

export const FIXED_SLOTS: ClassSlot[] = [
  { slot: 1, startTime: '07:10', endTime: '08:00', label: 'Slot 1 (07:10 - 08:00)' },
  { slot: 2, startTime: '08:00', endTime: '08:50', label: 'Slot 2 (08:00 - 08:50)' },
  { slot: 3, startTime: '09:20', endTime: '10:10', label: 'Slot 3 (09:20 - 10:10)' },
  { slot: 4, startTime: '10:10', endTime: '11:00', label: 'Slot 4 (10:10 - 11:00)' },
  { slot: 5, startTime: '11:10', endTime: '12:00', label: 'Slot 5 (11:10 - 12:00)' },
  { slot: 6, startTime: '12:00', endTime: '12:50', label: 'Slot 6 (12:00 - 12:50)' },
];

export const BREAK_TIMES = [
  { afterSlot: 2, startTime: '08:50', endTime: '09:20', duration: '30 min', label: 'Morning Refreshment Break' },
  { afterSlot: 4, startTime: '11:00', endTime: '11:10', duration: '10 min', label: 'Short Transition Break' },
  { afterSlot: 6, startTime: '12:50', endTime: '13:00', duration: '10 min', label: 'Afternoon Transition Break' },
];

export function createMockStudent(
  universityId: string = '',
  semester: 'Odd' | 'Even' = 'Odd',
  academicYear: string = '2026-27'
): StudentProfile {
  const cleanId = (universityId || '').trim();
  return {
    studentId: cleanId || 'Student',
    universityId: cleanId || 'Student',
    name: 'Student',
    program: 'B.Tech',
    branch: 'Computer Science and Engineering',
    section: 'S-1-A',
    semester,
    academicYear,
    email: cleanId ? `${cleanId}@kluniversity.in` : 'student@kluniversity.in',
    avatar: cleanId ? cleanId.charAt(0).toUpperCase() : 'S',
    cgpa: 8.85,
    advisor: 'Academic Coordinator',
    isMockData: true,
  };
}

export const DEMO_STUDENT: StudentProfile = createMockStudent('', 'Odd', '2026-27');

export const DEMO_COURSES: CourseInfo[] = [
  {
    code: '26SC1101',
    name: 'Problem Solving Using Programming (Java)',
    type: 'Core Computing / Lab Integrated',
    credits: 4,
    faculty: 'Dr. P. V. Ramana',
    weeklyClasses: 12,
    color: '#B8FF00', // Neon lime
    primaryRoom: 'F108 / F202A',
    description: 'Object-oriented programming, data structures fundamentals, algorithmic thinking, and hands-on Java problem solving.',
  },
  {
    code: '26MT1101',
    name: 'Mathematics for Computation',
    type: 'Core Engineering Mathematics',
    credits: 4,
    faculty: 'Prof. S. R. Murthy',
    weeklyClasses: 6,
    color: '#6433FF', // Electric purple
    primaryRoom: 'F105',
    description: 'Discrete mathematics, linear algebra matrices, combinatorics, graph theory, and mathematical foundations for computer science.',
  },
  {
    code: '26UC1137',
    name: 'Design Thinking for Innovation & Entrepreneurship',
    type: 'University Core',
    credits: 3,
    faculty: 'Dr. Ananya Roy',
    weeklyClasses: 5,
    color: '#FF2468', // Vibrant pink
    primaryRoom: 'F107 / S513',
    description: 'Human-centered design, prototyping, empathy mapping, customer discovery, and entrepreneurial venture creation.',
  },
  {
    code: '26UC1102',
    name: 'Language Skills for Engineers',
    type: 'University Core',
    credits: 3,
    faculty: 'Dr. M. Lakshmi',
    weeklyClasses: 5,
    color: '#00E5FF', // Electric Cyan
    primaryRoom: 'F105 / F301A / F309',
    description: 'Professional engineering communication, technical report writing, spoken eloquence, presentation skills, and vocabulary mastery.',
  },
];

export const DEMO_ATTENDANCE_OVERALL: OverallAttendance = {
  percentage: 86.4,
  totalClasses: 110,
  attended: 95,
  absent: 15,
  status: 'good',
  lastUpdated: '10 minutes ago',
};

export const DEMO_ATTENDANCE_SUBJECTS: AttendanceRecord[] = [
  {
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    faculty: 'Dr. P. V. Ramana',
    totalClasses: 48,
    attended: 42,
    absent: 6,
    percentage: 87.5,
    lastUpdated: '15 minutes ago',
    status: 'good',
  },
  {
    courseCode: '26MT1101',
    courseName: 'Mathematics for Computation',
    faculty: 'Prof. S. R. Murthy',
    totalClasses: 26,
    attended: 21,
    absent: 5,
    percentage: 80.8,
    lastUpdated: '2 hours ago',
    status: 'warning',
  },
  {
    courseCode: '26UC1137',
    courseName: 'Design Thinking for Innovation & Entrepreneurship',
    faculty: 'Dr. Ananya Roy',
    totalClasses: 20,
    attended: 18,
    absent: 2,
    percentage: 90.0,
    lastUpdated: 'Today, 11:30 AM',
    status: 'good',
  },
  {
    courseCode: '26UC1102',
    courseName: 'Language Skills for Engineers',
    faculty: 'Dr. M. Lakshmi',
    totalClasses: 16,
    attended: 14,
    absent: 2,
    percentage: 87.5,
    lastUpdated: 'Yesterday',
    status: 'good',
  },
];

export const DEMO_TIMETABLE: TimetableEntry[] = [
  // --- MONDAY ---
  {
    id: 'mon-1',
    day: 'Monday',
    slot: 1,
    startTime: '07:10',
    endTime: '08:00',
    courseCode: '26MT1101',
    courseName: 'Mathematics for Computation',
    classType: 'L',
    section: 'S-1-A',
    room: 'F105',
    faculty: 'Prof. S. R. Murthy',
  },
  {
    id: 'mon-2',
    day: 'Monday',
    slot: 2,
    startTime: '08:00',
    endTime: '08:50',
    courseCode: '26MT1101',
    courseName: 'Mathematics for Computation',
    classType: 'L',
    section: 'S-1-A',
    room: 'F105',
    faculty: 'Prof. S. R. Murthy',
  },
  {
    id: 'mon-3',
    day: 'Monday',
    slot: 3,
    startTime: '09:20',
    endTime: '10:10',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'L',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'mon-4',
    day: 'Monday',
    slot: 4,
    startTime: '10:10',
    endTime: '11:00',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'L',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'mon-5',
    day: 'Monday',
    slot: 5,
    startTime: '11:10',
    endTime: '12:00',
    courseCode: '26UC1137',
    courseName: 'Design Thinking for Innovation & Entrepreneurship',
    classType: 'P',
    section: 'S-1-A',
    room: 'F107',
    faculty: 'Dr. Ananya Roy',
  },
  {
    id: 'mon-6',
    day: 'Monday',
    slot: 6,
    startTime: '12:00',
    endTime: '12:50',
    courseCode: '26UC1102',
    courseName: 'Language Skills for Engineers',
    classType: 'P',
    section: 'S-1-A',
    room: 'F105',
    faculty: 'Dr. M. Lakshmi',
  },

  // --- TUESDAY ---
  {
    id: 'tue-1',
    day: 'Tuesday',
    slot: 1,
    startTime: '07:10',
    endTime: '08:00',
    courseCode: '26MT1101',
    courseName: 'Mathematics for Computation',
    classType: 'L',
    section: 'S-1-A',
    room: 'F105',
    faculty: 'Prof. S. R. Murthy',
  },
  {
    id: 'tue-2',
    day: 'Tuesday',
    slot: 2,
    startTime: '08:00',
    endTime: '08:50',
    courseCode: '26MT1101',
    courseName: 'Mathematics for Computation',
    classType: 'L',
    section: 'S-1-A',
    room: 'F105',
    faculty: 'Prof. S. R. Murthy',
  },
  {
    id: 'tue-3',
    day: 'Tuesday',
    slot: 3,
    startTime: '09:20',
    endTime: '10:10',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'tue-4',
    day: 'Tuesday',
    slot: 4,
    startTime: '10:10',
    endTime: '11:00',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'tue-5',
    day: 'Tuesday',
    slot: 5,
    startTime: '11:10',
    endTime: '12:00',
    courseCode: '26UC1102',
    courseName: 'Language Skills for Engineers',
    classType: 'P',
    section: 'S-1-A',
    room: 'F301A',
    faculty: 'Dr. M. Lakshmi',
  },
  {
    id: 'tue-6',
    day: 'Tuesday',
    slot: 6,
    startTime: '12:00',
    endTime: '12:50',
    courseCode: '26UC1102',
    courseName: 'Language Skills for Engineers',
    classType: 'P',
    section: 'S-1-A',
    room: 'F301A',
    faculty: 'Dr. M. Lakshmi',
  },

  // --- WEDNESDAY ---
  {
    id: 'wed-1',
    day: 'Wednesday',
    slot: 1,
    startTime: '07:10',
    endTime: '08:00',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F202A',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'wed-2',
    day: 'Wednesday',
    slot: 2,
    startTime: '08:00',
    endTime: '08:50',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F202A',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'wed-3',
    day: 'Wednesday',
    slot: 3,
    startTime: '09:20',
    endTime: '10:10',
    courseCode: '26UC1137',
    courseName: 'Design Thinking for Innovation & Entrepreneurship',
    classType: 'P',
    section: 'S-1-A',
    room: 'S513',
    faculty: 'Dr. Ananya Roy',
  },
  {
    id: 'wed-4',
    day: 'Wednesday',
    slot: 4,
    startTime: '10:10',
    endTime: '11:00',
    courseCode: '26UC1137',
    courseName: 'Design Thinking for Innovation & Entrepreneurship',
    classType: 'P',
    section: 'S-1-A',
    room: 'S513',
    faculty: 'Dr. Ananya Roy',
  },
  {
    id: 'wed-5',
    day: 'Wednesday',
    slot: 5,
    startTime: '11:10',
    endTime: '12:00',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'wed-6',
    day: 'Wednesday',
    slot: 6,
    startTime: '12:00',
    endTime: '12:50',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },

  // --- THURSDAY ---
  {
    id: 'thu-1',
    day: 'Thursday',
    slot: 1,
    startTime: '07:10',
    endTime: '08:00',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F202A',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'thu-2',
    day: 'Thursday',
    slot: 2,
    startTime: '08:00',
    endTime: '08:50',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F202A',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'thu-3',
    day: 'Thursday',
    slot: 3,
    startTime: '09:20',
    endTime: '10:10',
    courseCode: '26UC1137',
    courseName: 'Design Thinking for Innovation & Entrepreneurship',
    classType: 'P',
    section: 'S-1-A',
    room: 'S513',
    faculty: 'Dr. Ananya Roy',
  },
  {
    id: 'thu-4',
    day: 'Thursday',
    slot: 4,
    startTime: '10:10',
    endTime: '11:00',
    courseCode: '26UC1137',
    courseName: 'Design Thinking for Innovation & Entrepreneurship',
    classType: 'P',
    section: 'S-1-A',
    room: 'S513',
    faculty: 'Dr. Ananya Roy',
  },

  // --- FRIDAY ---
  {
    id: 'fri-3',
    day: 'Friday',
    slot: 3,
    startTime: '09:20',
    endTime: '10:10',
    courseCode: '26MT1101',
    courseName: 'Mathematics for Computation',
    classType: 'T',
    section: 'S-1-A',
    room: 'F105',
    faculty: 'Prof. S. R. Murthy',
  },
  {
    id: 'fri-4',
    day: 'Friday',
    slot: 4,
    startTime: '10:10',
    endTime: '11:00',
    courseCode: '26MT1101',
    courseName: 'Mathematics for Computation',
    classType: 'T',
    section: 'S-1-A',
    room: 'F105',
    faculty: 'Prof. S. R. Murthy',
  },
  {
    id: 'fri-5',
    day: 'Friday',
    slot: 5,
    startTime: '11:10',
    endTime: '12:00',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'fri-6',
    day: 'Friday',
    slot: 6,
    startTime: '12:00',
    endTime: '12:50',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },

  // --- SATURDAY ---
  {
    id: 'sat-3',
    day: 'Saturday',
    slot: 3,
    startTime: '09:20',
    endTime: '10:10',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'sat-4',
    day: 'Saturday',
    slot: 4,
    startTime: '10:10',
    endTime: '11:00',
    courseCode: '26SC1101',
    courseName: 'Problem Solving Using Programming (Java)',
    classType: 'S',
    section: 'S-1-A',
    room: 'F108',
    faculty: 'Dr. P. V. Ramana',
  },
  {
    id: 'sat-5',
    day: 'Saturday',
    slot: 5,
    startTime: '11:10',
    endTime: '12:00',
    courseCode: '26UC1102',
    courseName: 'Language Skills for Engineers',
    classType: 'P',
    section: 'S-1-A',
    room: 'F309',
    faculty: 'Dr. M. Lakshmi',
  },
  {
    id: 'sat-6',
    day: 'Saturday',
    slot: 6,
    startTime: '12:00',
    endTime: '12:50',
    courseCode: '26UC1102',
    courseName: 'Language Skills for Engineers',
    classType: 'P',
    section: 'S-1-A',
    room: 'F309',
    faculty: 'Dr. M. Lakshmi',
  },
];

export interface RoomDetail {
  code: string;
  building: string;
  floor: string;
  block: string;
  capacity: number;
  type: string;
  facilities: string[];
  directions: string;
}

export const ROOM_DATABASE: Record<string, RoomDetail> = {
  F105: {
    code: 'F105',
    building: 'FedEx / Main Academic Block',
    floor: '1st Floor',
    block: 'F-Block North',
    capacity: 70,
    type: 'Smart Lecture Classroom',
    facilities: ['High-definition Projector', 'Acoustic Sound System', 'Air Conditioned', 'Tiered Seating'],
    directions: 'Take the main staircase to Floor 1, turn right down the east corridor. Room F105 is the third door on the right.',
  },
  F108: {
    code: 'F108',
    building: 'FedEx / Main Academic Block',
    floor: '1st Floor',
    block: 'F-Block Computing Wing',
    capacity: 65,
    type: 'Interactive Computing Lab & Lecture Hall',
    facilities: ['Dual Display Terminals', 'Gigabit Ethernet Ports', 'High-speed Wi-Fi', 'Smart Whiteboard'],
    directions: 'Located next to the central server lab on the 1st floor, F-block west corridor.',
  },
  F107: {
    code: 'F107',
    building: 'FedEx / Main Academic Block',
    floor: '1st Floor',
    block: 'F-Block Central',
    capacity: 60,
    type: 'Innovation & Design Studio',
    facilities: ['Modular Whiteboards', 'Collaborative Round Tables', 'Maker Prototyping Benches'],
    directions: '1st Floor between Room F106 and F108.',
  },
  F301A: {
    code: 'F301A',
    building: 'FedEx / Main Academic Block',
    floor: '3rd Floor',
    block: 'F-Block Humanities & Language Lab',
    capacity: 45,
    type: 'Digital Language Laboratory',
    facilities: ['Audio Headsets with Mic', 'Interactive Speech Recognition Terminals', 'Central Audio Console'],
    directions: 'Take lift to 3rd floor, turn left toward Language Department.',
  },
  F202A: {
    code: 'F202A',
    building: 'FedEx / Main Academic Block',
    floor: '2nd Floor',
    block: 'F-Block Software Lab',
    capacity: 75,
    type: 'Advanced Software Engineering Lab',
    facilities: ['Intel i7 Development Workstations', 'Linux & Windows Dual Boot', 'Overhead Projector'],
    directions: '2nd Floor, central software development zone.',
  },
  S513: {
    code: 'S513',
    building: 'Science & Technology Tower (S-Block)',
    floor: '5th Floor',
    block: 'S-Block West Wing',
    capacity: 55,
    type: 'Design Thinking & Incubation Arena',
    facilities: ['Sticky Wall Canvas', '3D Printer Access', 'Video Conferencing Pods'],
    directions: 'Enter S-Block Tower, take elevators to 5th floor, walk past the Incubation Hub.',
  },
  F309: {
    code: 'F309',
    building: 'FedEx / Main Academic Block',
    floor: '3rd Floor',
    block: 'F-Block East Wing',
    capacity: 50,
    type: 'Communication Skills Studio',
    facilities: ['Podium Presentation Cam', 'Surround Mics', 'Projector Screen'],
    directions: '3rd Floor East corridor, near Faculty Lounge 3.',
  },
};
